name: 'simmc-fusion'
data_folder: 'data/simmc/simmc_fashion/'
cache_dir:

remove_space: False
use_loss_eval: True
to_save_model: True
save_model_file: "../model/furniture/%s/best_model"
load_model_file: "../model/furniture/%s/best_model"

# optimization
num_epoch: 10
gradient_clip: 1
adam_epsilon: 1e-8
warmup_steps: 0

